[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q
norecursedirs =
    .git
    .pytest_cache
    __pycache__
    venv
    data
    backup
    tmp
    scripts
    static
